server:
  port: 8083

spring:
  application:
    name: sync-bridge

  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin

bridge:
  blue-service-url: http://localhost:8081
  green-service-url: http://localhost:8082
  datasource:
    blue:
      jdbc-url: jdbc:mysql://localhost:3307/catalog_v1?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
    green:
      jdbc-url: jdbc:mysql://localhost:3308/catalog_v2?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
  poll-interval-ms: 2000
  batch-size: 50

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics

logging:
  level:
    com.hirono.bridge: DEBUG
    org.hibernate.SQL: WARN