server:
  port: 8081

spring:
  application:
    name: blue-service
  datasource:
    url: jdbc:mysql://localhost:3307/catalog_v1?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
  liquibase:
    change-log: classpath:db/changelog/v1-changelog.xml
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics

logging:
  level:
    com.hirono.blue: DEBUG
    liquibase: INFO